services:
  app:
    build: .docker
    stdin_open: true
    tty: true
    container_name: app.VaradifiBack
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "3000:3000"
      - "8080:8080"
    expose:
      - "3000"
      - "8080"
    volumes:
      - .:/app
      # exclude
      - /app/.git/
    working_dir: /app
    user: 1000:1000
  mysql:
    image: mysql:8.0.27
    container_name: mysql.varadifi
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: varadifi
      MYSQL_USER: varadifi
      MYSQL_PASSWORD: varadifi
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: pma.varadifi
    ports:
      - "4577:80"
    environment:
      PMA_HOST: mysql.varadifi
      PMA_USER: varadifi
      PMA_PASSWORD: varadifi
      UPLOAD_LIMIT: 250M

volumes:
  mysql_data:
    driver: local
